// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZGT.Trouble.PL.Data;

#nullable disable

namespace ZGT.Trouble.PL.Migrations
{
    [DbContext(typeof(TroubleEntities))]
    [Migration("20241201213143_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZGT.Trouble.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BlueCenterSquare1")
                        .HasColumnType("int");

                    b.Property<int>("BlueCenterSquare2")
                        .HasColumnType("int");

                    b.Property<int>("BlueCenterSquare3")
                        .HasColumnType("int");

                    b.Property<int>("BlueCenterSquare4")
                        .HasColumnType("int");

                    b.Property<int>("BlueHomeSquare1")
                        .HasColumnType("int");

                    b.Property<int>("BlueHomeSquare2")
                        .HasColumnType("int");

                    b.Property<int>("BlueHomeSquare3")
                        .HasColumnType("int");

                    b.Property<int>("BlueHomeSquare4")
                        .HasColumnType("int");

                    b.Property<string>("BlueStartSquare")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("DieRoll")
                        .HasColumnType("int");

                    b.Property<int>("GameComplete")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameStartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("GreenCenterSquare1")
                        .HasColumnType("int");

                    b.Property<int>("GreenCenterSquare2")
                        .HasColumnType("int");

                    b.Property<int>("GreenCenterSquare3")
                        .HasColumnType("int");

                    b.Property<int>("GreenCenterSquare4")
                        .HasColumnType("int");

                    b.Property<int>("GreenHomeSquare1")
                        .HasColumnType("int");

                    b.Property<int>("GreenHomeSquare2")
                        .HasColumnType("int");

                    b.Property<int>("GreenHomeSquare3")
                        .HasColumnType("int");

                    b.Property<int>("GreenHomeSquare4")
                        .HasColumnType("int");

                    b.Property<string>("GreenStartSquare")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PlayerTurn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RedCenterSquare1")
                        .HasColumnType("int");

                    b.Property<int>("RedCenterSquare2")
                        .HasColumnType("int");

                    b.Property<int>("RedCenterSquare3")
                        .HasColumnType("int");

                    b.Property<int>("RedCenterSquare4")
                        .HasColumnType("int");

                    b.Property<int>("RedHomeSquare1")
                        .HasColumnType("int");

                    b.Property<int>("RedHomeSquare2")
                        .HasColumnType("int");

                    b.Property<int>("RedHomeSquare3")
                        .HasColumnType("int");

                    b.Property<int>("RedHomeSquare4")
                        .HasColumnType("int");

                    b.Property<string>("RedStartSquare")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square10")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square11")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square12")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square13")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square14")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square15")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square16")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square17")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square18")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square19")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square2")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square20")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square21")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square22")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square23")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square24")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square3")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square4")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square5")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square6")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square7")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square8")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Square9")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("YellowCenterSquare1")
                        .HasColumnType("int");

                    b.Property<int>("YellowCenterSquare2")
                        .HasColumnType("int");

                    b.Property<int>("YellowCenterSquare3")
                        .HasColumnType("int");

                    b.Property<int>("YellowCenterSquare4")
                        .HasColumnType("int");

                    b.Property<int>("YellowHomeSquare1")
                        .HasColumnType("int");

                    b.Property<int>("YellowHomeSquare2")
                        .HasColumnType("int");

                    b.Property<int>("YellowHomeSquare3")
                        .HasColumnType("int");

                    b.Property<int>("YellowHomeSquare4")
                        .HasColumnType("int");

                    b.Property<string>("YellowStartSquare")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0e00542-a4bd-4088-b912-0dae885cb214"),
                            BlueCenterSquare1 = 0,
                            BlueCenterSquare2 = 0,
                            BlueCenterSquare3 = 0,
                            BlueCenterSquare4 = 0,
                            BlueHomeSquare1 = 1,
                            BlueHomeSquare2 = 1,
                            BlueHomeSquare3 = 1,
                            BlueHomeSquare4 = 1,
                            BlueStartSquare = "",
                            DieRoll = 6,
                            GameComplete = 0,
                            GameStartDate = new DateTime(2024, 12, 1, 15, 31, 42, 305, DateTimeKind.Local).AddTicks(568),
                            GreenCenterSquare1 = 0,
                            GreenCenterSquare2 = 0,
                            GreenCenterSquare3 = 0,
                            GreenCenterSquare4 = 0,
                            GreenHomeSquare1 = 1,
                            GreenHomeSquare2 = 1,
                            GreenHomeSquare3 = 1,
                            GreenHomeSquare4 = 1,
                            GreenStartSquare = "",
                            PlayerTurn = "Yellow",
                            RedCenterSquare1 = 0,
                            RedCenterSquare2 = 0,
                            RedCenterSquare3 = 0,
                            RedCenterSquare4 = 0,
                            RedHomeSquare1 = 1,
                            RedHomeSquare2 = 1,
                            RedHomeSquare3 = 1,
                            RedHomeSquare4 = 1,
                            RedStartSquare = "",
                            Square1 = "",
                            Square10 = "",
                            Square11 = "",
                            Square12 = "",
                            Square13 = "",
                            Square14 = "",
                            Square15 = "",
                            Square16 = "",
                            Square17 = "",
                            Square18 = "",
                            Square19 = "",
                            Square2 = "",
                            Square20 = "",
                            Square21 = "",
                            Square22 = "",
                            Square23 = "",
                            Square24 = "",
                            Square3 = "",
                            Square4 = "",
                            Square5 = "",
                            Square6 = "",
                            Square7 = "",
                            Square8 = "",
                            Square9 = "",
                            YellowCenterSquare1 = 0,
                            YellowCenterSquare2 = 0,
                            YellowCenterSquare3 = 0,
                            YellowCenterSquare4 = 0,
                            YellowHomeSquare1 = 1,
                            YellowHomeSquare2 = 1,
                            YellowHomeSquare3 = 1,
                            YellowHomeSquare4 = 1,
                            YellowStartSquare = ""
                        },
                        new
                        {
                            Id = new Guid("4a28deab-4f05-4cd9-a129-3a1de188fe21"),
                            BlueCenterSquare1 = 0,
                            BlueCenterSquare2 = 0,
                            BlueCenterSquare3 = 0,
                            BlueCenterSquare4 = 0,
                            BlueHomeSquare1 = 1,
                            BlueHomeSquare2 = 1,
                            BlueHomeSquare3 = 1,
                            BlueHomeSquare4 = 1,
                            BlueStartSquare = "",
                            DieRoll = 1,
                            GameComplete = 0,
                            GameStartDate = new DateTime(2024, 12, 1, 15, 31, 42, 305, DateTimeKind.Local).AddTicks(642),
                            GreenCenterSquare1 = 0,
                            GreenCenterSquare2 = 0,
                            GreenCenterSquare3 = 0,
                            GreenCenterSquare4 = 0,
                            GreenHomeSquare1 = 1,
                            GreenHomeSquare2 = 1,
                            GreenHomeSquare3 = 1,
                            GreenHomeSquare4 = 1,
                            GreenStartSquare = "",
                            PlayerTurn = "Yellow",
                            RedCenterSquare1 = 0,
                            RedCenterSquare2 = 0,
                            RedCenterSquare3 = 0,
                            RedCenterSquare4 = 0,
                            RedHomeSquare1 = 1,
                            RedHomeSquare2 = 1,
                            RedHomeSquare3 = 1,
                            RedHomeSquare4 = 1,
                            RedStartSquare = "",
                            Square1 = "",
                            Square10 = "",
                            Square11 = "",
                            Square12 = "",
                            Square13 = "",
                            Square14 = "",
                            Square15 = "",
                            Square16 = "",
                            Square17 = "",
                            Square18 = "",
                            Square19 = "",
                            Square2 = "",
                            Square20 = "",
                            Square21 = "",
                            Square22 = "",
                            Square23 = "",
                            Square24 = "",
                            Square3 = "",
                            Square4 = "",
                            Square5 = "",
                            Square6 = "",
                            Square7 = "",
                            Square8 = "",
                            Square9 = "",
                            YellowCenterSquare1 = 0,
                            YellowCenterSquare2 = 0,
                            YellowCenterSquare3 = 0,
                            YellowCenterSquare4 = 0,
                            YellowHomeSquare1 = 1,
                            YellowHomeSquare2 = 1,
                            YellowHomeSquare3 = 1,
                            YellowHomeSquare4 = 1,
                            YellowStartSquare = ""
                        },
                        new
                        {
                            Id = new Guid("f582eaf5-0f38-44db-be25-3c0bafdf2e18"),
                            BlueCenterSquare1 = 0,
                            BlueCenterSquare2 = 0,
                            BlueCenterSquare3 = 0,
                            BlueCenterSquare4 = 0,
                            BlueHomeSquare1 = 1,
                            BlueHomeSquare2 = 1,
                            BlueHomeSquare3 = 1,
                            BlueHomeSquare4 = 1,
                            BlueStartSquare = "",
                            DieRoll = 3,
                            GameComplete = 0,
                            GameStartDate = new DateTime(2024, 12, 1, 15, 31, 42, 305, DateTimeKind.Local).AddTicks(670),
                            GreenCenterSquare1 = 0,
                            GreenCenterSquare2 = 0,
                            GreenCenterSquare3 = 0,
                            GreenCenterSquare4 = 0,
                            GreenHomeSquare1 = 1,
                            GreenHomeSquare2 = 1,
                            GreenHomeSquare3 = 1,
                            GreenHomeSquare4 = 1,
                            GreenStartSquare = "",
                            PlayerTurn = "Yellow",
                            RedCenterSquare1 = 0,
                            RedCenterSquare2 = 0,
                            RedCenterSquare3 = 0,
                            RedCenterSquare4 = 0,
                            RedHomeSquare1 = 1,
                            RedHomeSquare2 = 1,
                            RedHomeSquare3 = 1,
                            RedHomeSquare4 = 1,
                            RedStartSquare = "",
                            Square1 = "",
                            Square10 = "",
                            Square11 = "",
                            Square12 = "",
                            Square13 = "",
                            Square14 = "",
                            Square15 = "",
                            Square16 = "",
                            Square17 = "",
                            Square18 = "",
                            Square19 = "",
                            Square2 = "",
                            Square20 = "",
                            Square21 = "",
                            Square22 = "",
                            Square23 = "",
                            Square24 = "",
                            Square3 = "",
                            Square4 = "",
                            Square5 = "",
                            Square6 = "",
                            Square7 = "",
                            Square8 = "",
                            Square9 = "",
                            YellowCenterSquare1 = 0,
                            YellowCenterSquare2 = 0,
                            YellowCenterSquare3 = 0,
                            YellowCenterSquare4 = 0,
                            YellowHomeSquare1 = 1,
                            YellowHomeSquare2 = 1,
                            YellowHomeSquare3 = 1,
                            YellowHomeSquare4 = 1,
                            YellowStartSquare = ""
                        });
                });

            modelBuilder.Entity("ZGT.Trouble.PL.Entities.tblPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("NumberOfWins")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayer_Id");

                    b.ToTable("tblPlayer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0e00542-a4bd-4088-b912-0dae885cb215"),
                            DateJoined = new DateTime(2024, 12, 1, 15, 31, 42, 304, DateTimeKind.Local).AddTicks(7193),
                            Email = "Glen@Glen",
                            NumberOfWins = 0,
                            Password = "12345",
                            UserName = "Glen"
                        },
                        new
                        {
                            Id = new Guid("ae3c2b78-e1b0-4956-adf1-34bf834e7583"),
                            DateJoined = new DateTime(2024, 12, 1, 15, 31, 42, 304, DateTimeKind.Local).AddTicks(7309),
                            Email = "Zach@Zach",
                            NumberOfWins = 0,
                            Password = "123",
                            UserName = "Zach"
                        },
                        new
                        {
                            Id = new Guid("756e7429-79d3-4179-8e38-7b8516893c07"),
                            DateJoined = new DateTime(2024, 12, 1, 15, 31, 42, 304, DateTimeKind.Local).AddTicks(7313),
                            Email = "Brian@Brian",
                            NumberOfWins = 0,
                            Password = "maple",
                            UserName = "Brian"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DateJoined = new DateTime(2024, 12, 1, 15, 31, 42, 304, DateTimeKind.Local).AddTicks(7321),
                            Email = "computer@computer",
                            NumberOfWins = 0,
                            Password = "12345",
                            UserName = "Computer"
                        });
                });

            modelBuilder.Entity("ZGT.Trouble.PL.Entities.tblPlayerGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsComputerPlaying")
                        .HasColumnType("bit");

                    b.Property<string>("PlayerColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlayerGame_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tblPlayerGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0e00542-a4bd-4088-b912-0dae885cb216"),
                            GameId = new Guid("c0e00542-a4bd-4088-b912-0dae885cb214"),
                            IsComputerPlaying = false,
                            PlayerColor = "y",
                            PlayerId = new Guid("c0e00542-a4bd-4088-b912-0dae885cb215")
                        },
                        new
                        {
                            Id = new Guid("d82b820e-dfea-4934-b877-155ef5ea36e6"),
                            GameId = new Guid("4a28deab-4f05-4cd9-a129-3a1de188fe21"),
                            IsComputerPlaying = false,
                            PlayerColor = "y",
                            PlayerId = new Guid("ae3c2b78-e1b0-4956-adf1-34bf834e7583")
                        },
                        new
                        {
                            Id = new Guid("0fe79625-d6ed-469a-9c08-c719f3245eb3"),
                            GameId = new Guid("f582eaf5-0f38-44db-be25-3c0bafdf2e18"),
                            IsComputerPlaying = false,
                            PlayerColor = "y",
                            PlayerId = new Guid("756e7429-79d3-4179-8e38-7b8516893c07")
                        },
                        new
                        {
                            Id = new Guid("7f626c72-4be5-4a0a-b8a4-b8c34dc69137"),
                            GameId = new Guid("c0e00542-a4bd-4088-b912-0dae885cb214"),
                            IsComputerPlaying = false,
                            PlayerColor = "b",
                            PlayerId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bb3e8235-c3b0-4835-a86e-da9d51fca467"),
                            GameId = new Guid("c0e00542-a4bd-4088-b912-0dae885cb214"),
                            IsComputerPlaying = false,
                            PlayerColor = "r",
                            PlayerId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("ce896b31-2ef3-40f7-99ff-2464fcac01f4"),
                            GameId = new Guid("c0e00542-a4bd-4088-b912-0dae885cb214"),
                            IsComputerPlaying = false,
                            PlayerColor = "g",
                            PlayerId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("f9ab93cd-3225-4ee6-89c3-c887dec88595"),
                            GameId = new Guid("4a28deab-4f05-4cd9-a129-3a1de188fe21"),
                            IsComputerPlaying = false,
                            PlayerColor = "b",
                            PlayerId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("ZGT.Trouble.PL.Entities.tblPlayerGame", b =>
                {
                    b.HasOne("ZGT.Trouble.PL.Entities.tblGame", "Game")
                        .WithMany("PlayerGame")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("FK_tblPlayerGame_GameId");

                    b.HasOne("ZGT.Trouble.PL.Entities.tblPlayer", "Player")
                        .WithMany("PlayerGame")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK_tblPlayerGame_PlayerId");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ZGT.Trouble.PL.Entities.tblGame", b =>
                {
                    b.Navigation("PlayerGame");
                });

            modelBuilder.Entity("ZGT.Trouble.PL.Entities.tblPlayer", b =>
                {
                    b.Navigation("PlayerGame");
                });
#pragma warning restore 612, 618
        }
    }
}
